version: "3.9"
services:
  db:
    image: mysql:8.0
    container_name: statdb
    command: --default-authentication-plugin=mysql_native_password
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: rootpw
      MYSQL_DATABASE: metrics
      MYSQL_USER: appuser
      MYSQL_PASSWORD: secretpass
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:

